# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_homepageslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageslider',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepageslider',
            name='url',
            field=models.URLField(default=True),
            preserve_default=False,
        ),
    ]
