# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20160208_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
