# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 05:00
from __future__ import unicode_literals

import care.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarePointBankDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_no', models.CharField(max_length=50)),
                ('vat_no', models.CharField(max_length=50)),
                ('benifit_name', models.CharField(max_length=50)),
                ('acc_no', models.CharField(max_length=50)),
                ('neft', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=50)),
                ('acc_type', models.CharField(choices=[('saving', 'Saving'), ('current', 'Current')], default='saving', max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarePointDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proof', models.FileField(blank=True, null=True, upload_to=care.models.user_doc_upload_to)),
                ('pan_card', models.FileField(blank=True, null=True, upload_to=care.models.user_doc_upload_to)),
                ('bank_pass', models.FileField(blank=True, null=True, upload_to=care.models.user_doc_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='CarePointPincode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=6, unique=True)),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarePointUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=20, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=care.models.user_pic_upload_to)),
                ('is_care', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=200, null=True)),
                ('answer', models.TextField(blank=True, max_length=200, null=True)),
                ('pub_date', models.DateTimeField(verbose_name='date_published')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Taluka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taluka', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='care.CarePointUserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='carepointpincode',
            name='taluka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care.Taluka'),
        ),
        migrations.AddField(
            model_name='carepointdocuments',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='care.CarePointUserProfile'),
        ),
        migrations.AddField(
            model_name='carepointbankdetail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='care.CarePointUserProfile'),
        ),
    ]
