# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendSMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateTimeField(auto_now_add=True)),
                ('sms_subject', models.CharField(max_length=80)),
                ('sms_text', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='SmsHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('recipient', models.CharField(max_length=50)),
                ('sms_subject', models.CharField(max_length=80)),
                ('sms_text', models.CharField(max_length=512)),
                ('sms_type', models.CharField(max_length=32)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmsMarketing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sms_subject', models.CharField(max_length=80)),
                ('sms_text', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='SmsSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_username', models.CharField(max_length=120)),
                ('sms_hashcode', models.CharField(max_length=200)),
                ('sms_sender', models.CharField(max_length=120)),
                ('sms_api', models.CharField(max_length=200)),
            ],
        ),
    ]
