# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sms', '0001_initial'),
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendsms',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.SignUp'),
        ),
    ]
