# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 07:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendsms',
            name='date1',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 14, 7, 44, 24, 250518, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendsms',
            name='sms_subject',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendsms',
            name='sms_text',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendsms',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccount.SignUp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smshistory',
            name='sms_type',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
