# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_sendsms_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkSms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('numbers', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BulkSmsHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('recipient', models.CharField(max_length=50)),
                ('sms_subject', models.CharField(max_length=80)),
                ('sms_text', models.CharField(max_length=512)),
                ('sms_type', models.CharField(max_length=32)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
