# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_sendsms_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
