# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 10:51
from __future__ import unicode_literals

import UI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BottomOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('offer', models.ImageField(help_text='for better display upload 570px width and 180px height image', upload_to=UI.models.top_offers_image_upload_to)),
                ('url', models.URLField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('offer', models.ImageField(help_text='for better display upload 270px width and 190px height image', upload_to=UI.models.top_offers_image_upload_to)),
                ('url', models.URLField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to=UI.models.logo_image_upload_to)),
            ],
        ),
    ]
