# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 13:06
from __future__ import unicode_literals

import UI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BottomOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('offer', models.ImageField(help_text='for better display upload 570px width and 180px height image', upload_to=UI.models.top_offers_image_upload_to)),
                ('url', models.URLField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=120)),
                ('page_type', models.CharField(choices=[('ContentBased', 'Content Based'), ('RedirectToLink', 'Redirect To Link')], default='ContentBased', max_length=120)),
                ('url', models.URLField(blank=True)),
                ('content', models.TextField(blank=True, max_length=10000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('show_on_page', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('offer', models.ImageField(help_text='for better display upload 270px width and 190px height image', upload_to=UI.models.top_offers_image_upload_to)),
                ('url', models.URLField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to=UI.models.logo_image_upload_to)),
            ],
        ),
    ]
