# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 09:14
from __future__ import unicode_literals

import UI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to=UI.models.logo_image_upload_to)),
            ],
        ),
    ]
