# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 10:45
from __future__ import unicode_literals

import UI.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadlogo',
            name='height_field',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='uploadlogo',
            name='logo',
            field=models.ImageField(default=datetime.datetime(2016, 2, 16, 10, 45, 2, 116648, tzinfo=utc), height_field='height_field', upload_to=UI.models.logo_image_upload_to, width_field='width_field'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadlogo',
            name='width_field',
            field=models.IntegerField(default=300),
        ),
    ]
