# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=120)),
                ('page_type', models.CharField(choices=[('ContentBased', 'Content Based'), ('RedirectToLink', 'Redirect To Link')], default='ContentBased', max_length=120)),
                ('url', models.URLField(blank=True)),
                ('content', models.TextField(blank=True, max_length=10000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('show_on_page', models.BooleanField(default=True)),
            ],
        ),
    ]
