# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0002_pointofinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepage',
            name='is_it_location',
            field=models.BooleanField(default=False),
        ),
    ]
