# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 10:50
from __future__ import unicode_literals

import UI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0002_auto_20160216_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadlogo',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='uploadlogo',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='uploadlogo',
            name='logo',
            field=models.ImageField(upload_to=UI.models.logo_image_upload_to),
        ),
    ]
