# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productimage',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(height_field='height_field', upload_to=products.models.product_image_upload_to, width_field='width_field'),
        ),
    ]
