# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.SignUp'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=mptt.fields.TreeManyToManyField(to='products.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, to='products.ProductColor'),
        ),
        migrations.AddField(
            model_name='product',
            name='shirtsizes',
            field=models.ManyToManyField(blank=True, to='products.ShirtSize'),
        ),
        migrations.AddField(
            model_name='product',
            name='shoessizes',
            field=models.ManyToManyField(blank=True, to='products.ShoesSize'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.Category'),
        ),
    ]
