# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20160207_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='height_field',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='width_field',
            field=models.IntegerField(default=300),
        ),
    ]
