# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20160208_0459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(height_field=300, upload_to=products.models.product_image_upload_to, width_field=300),
        ),
    ]
