# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 08:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_order_id', models.IntegerField(blank=True)),
                ('admin_reason', models.TextField(max_length=300)),
                ('admin_order_name', models.CharField(blank=True, max_length=300)),
                ('admin_order_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('admin_user', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('dispatched', 'Dispatched'), ('intransist', 'Intransist'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='received', max_length=120)),
                ('shipping_total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=50)),
                ('payment', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('type', models.CharField(blank=True, choices=[('billing', 'Billing'), ('shipping', 'Shipping')], default='billing', max_length=120, null=True)),
                ('street', models.TextField()),
                ('postcode', models.CharField(max_length=6)),
                ('mobile', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True)),
                ('reason', models.TextField(max_length=300)),
                ('order_name', models.CharField(blank=True, max_length=300)),
                ('order_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('user', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='orders.UserAddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.Cart'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='orders.UserAddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
