# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 12:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20160223_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 23, 12, 50, 27, 87505, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
