# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20160312_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('dispatched', 'Dispatched'), ('intransist', 'Intransist'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='received', max_length=120),
        ),
    ]
