# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
