# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20160223_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='state',
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='street',
            field=models.TextField(),
        ),
    ]
